sudo: false
language: cpp
compiler:
- clang++
- g++
install:
- if [ "$CXX" = "g++" ]; then export CXXFLAGS="-std=c++11"; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    - llvm-toolchain-precise
    packages:
    - libpcap-dev
    - libncurses5-dev
    - clang-3.7
    - g++-5
    - gcc-5
script:
- make CXX="${CXX}"
notifications:
  slack:
    secure: o7KflC5GhgEov8Y/py4KVmkkcQQHaGOcicvPjSUeZ2cG6k76onKWYd53tudSjx8i7OiSMHEGybJtz5+OFsJqlm6AicSgMb/DjnPTOgf+yl8bkcCU8srPMfjXYCytGns9qnyBuCk1lrOrtEcSENgcY8RiY3Ie3r6wu/5+gBgbxBy0vGmOJ8SqidbWQBowkSGJDb3jSN5ddF9l+iVPj5j923LbEI9iQgxTAsKaao3JQnxtXJ/0qgDdkfynqolrsehCbWXIbXEfOugWcTi6mbp+8pfjjEasH9jhaCVPJYo4X8xxd9xYCDRawoQinZXwGsNi05lIZjA4SyHloi5pCo1sy8fkBsB7oP+eCZtSqrtAkGqo6zCMSq5sHSxCiT2pdGqaIMnS+HLlxLmV4nyPHrcVRlPADnNm3yonTj7BkkKosX1cgNQB186XJoCWc4HAKWQC2VqWPc/K5uOxjUpaRy+jAy0tQ/FPCYHReIezWYFz81sE7uQXIPnhINKUmNjnzcqA2gvgWH8IxDTIoWmDMKVtLVbiavx1Ia2bVdXoiSC8dC5MkoUzsdfSujrpUTIt0CO/ZJzZhXYcThbaRUpNjtO3Fwd9B7oBLUABNzF7WTE5CKMVvMpg4mOYONmqlcVUucV0TVu+PKy7KAdNtSuYDN/Tdmk5cCdmbcaKwhx2gqmSEus=
